### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by jordansexton** [solana-labs/solana-solidity.js#10]
Moved from #5 and #7

- [ ] Get all tests passing
- [ ] Document use cases
- [ ] Document the ability to reuse deployed contracts with new storage (a unique feature of Solana!)
- [ ] Document that lamports are needed in the payer account for simulation (for now)
- [ ] Explore and document the browser use case, build targets, and polyfills as needed
- [ ] Add quick starter project
- [x] Uncomment or remove all commented out blocks of executable code
- [x] Refactor out clone method
- [x] Document all public methods in more detail
- [x] Address all remaining TODO/FIXME comments
- [x] Revamp error types
- [x] Colocate unit and integration tests
- [x] Remove Makefile and use yarn scripts + shx (platform-indepedent and JS devs are more familiar with)
- [x] ~Finish ES modules configuration~

**Comment by seanyoung** [comment]
Added TODO from #9
